### PR TITLE
Cleaned up cucumber tests

### PR DESCRIPTION
**Pull request by townsend3721**
Condensed Cucumber tests so they were easier to read, created a few more steps.

### CODE REVIEW

**Comment by dantoth24** [comment]
Seems good to me, it doesn't seem like you changed anything that would conflict with the change I made in my PR.

**Comment by townsend3721** [comment]
Does it matter which one of us merges first?

**Comment by dstephens3** [comment]
Looks good to me as well.

**Review by harperiscoding — APPROVED** [review]
Much cleaner, good work.

**Pull request merged**
